from __future__ import annotations

import json

from tbyc_dataset import cli
from tbyc_dataset.extraction.regex_pipeline import extract_regex_artifacts_from_comment


def test_extract_regex_artifacts_from_comment_detects_problem_question_solution_and_code() -> None:
    text = """
    This seems like an 8.5 regression under coverage.
    ERROR: file 'foo.repo_mapping' is generated by these conflicting actions.
    Could you diff the two configs and see what's different?
    I think the fix is to move coverage_support to CoverageOptions and don't trim it.

    ```text
    ERROR: conflict in foo.repo_mapping
    ```
    """

    artifacts = extract_regex_artifacts_from_comment(text)
    artifact_types = {artifact["type"] for artifact in artifacts}

    assert "problem_statement" in artifact_types
    assert "question" in artifact_types
    assert "proposed_solution" in artifact_types
    assert "code_snippet" in artifact_types


def test_extract_discussion_artifacts_regex_cli_writes_issue_file(monkeypatch, tmp_path, capsys) -> None:
    processed_dir = tmp_path / "processed" / "octo__repo"
    processed_dir.mkdir(parents=True)
    curated_path = processed_dir / "curated.jsonl"
    row = {
        "issue_number": 7,
        "issue_url": "https://example.com/issues/7",
        "input_vector": {"title": "Config regression in coverage mode"},
        "deliberation_thread": [
            {
                "author_login": "alice",
                "body": "This is a regression. Could you compare the configs?",
                "is_issue_body": True,
                "url": "https://example.com/issues/7",
            },
            {
                "author_login": "bob",
                "body": "Try enabling the experimental flag as a workaround.",
                "is_issue_body": False,
                "url": "https://example.com/issues/7#issuecomment-1",
            },
        ],
    }
    curated_path.write_text(json.dumps(row) + "\n", encoding="utf-8")

    cli.main(
        [
            "extract-discussion-artifacts-regex",
            "--repo",
            "octo/repo",
            "--output-root",
            str(tmp_path),
        ]
    )

    payload = json.loads(capsys.readouterr().out)
    assert payload["repository"] == "octo/repo"
    assert payload["issue_count"] == 1

    issue_path = tmp_path / "extractions_regex" / "octo__repo" / "issue_7.json"
    issue_payload = json.loads(issue_path.read_text(encoding="utf-8"))
    assert issue_payload["extractor"] == "regex"
    assert issue_payload["issue"]["artifact_count"] >= 2
    assert issue_payload["issue"]["comments"][0]["artifact_count"] >= 1
